### ISSUE TITLE
Add Calibre-Web-Automated into Calibre web

### ISSUE THREAD

**Issue by compgeniuses** [geniusdynamics/dev#7]
This is a Suggestion for Adding calibre web automated into the Calibre web App for NS8
https://github.com/crocodilestick/Calibre-Web-Automated?ref=selfh.st

The App has been implemented as a docker compose setup, and is intended to make it eay to Upload files to calibrre web

```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=100
      - TZ=UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /path/to/config/folder:/config
      - /path/to/the/folder/you/want/to/use/for/book/ingest:/cwa-book-ingest
      - /path/to/your/calibre/library:/calibre-library
      #- /path/to/where/you/keep/your/books:/books #Optional
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 8084:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
    
```
